---
name: 🐛 Bug Report
description: Signaler un bug sur le site web
title: "[BUG] "
labels: ["bug", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 Description du bug
        Décrivez le bug de manière claire et concise.

  - type: input
    id: url
    attributes:
      label: URL de la page
      description: Sur quelle page avez-vous rencontré le bug ?
      placeholder: https://alphallm.tech/...
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Navigateur
      description: Quel navigateur utilisez-vous ?
      options:
        - Chrome/Chromium
        - Firefox
        - Safari
        - Edge
        - Autre (précisez)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description détaillée
      description: Décrivez étape par étape comment reproduire le bug
      placeholder: |
        1. Aller sur '...'
        2. Cliquer sur '...'
        3. Voir l'erreur
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportement attendu
      description: Que devrait-il se passer normalement ?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Comportement actuel
      description: Que se passe-t-il réellement ?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Captures d'écran
      description: Ajoutez des captures d'écran si possible

  - type: input
    id: os
    attributes:
      label: Système d'exploitation
      description: Windows, macOS, Linux, etc.
      placeholder: Windows 11

  - type: textarea
    id: additional
    attributes:
      label: Informations supplémentaires
      description: Toute autre information utile